/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalAssignmentsRouteImport } from './routes/portal.assignments'
import { Route as PortalConflictsRouteImport } from './routes/portal.conflicts'
import { Route as PortalDashboardRouteImport } from './routes/portal.dashboard'
import { Route as PortalHotspotsRouteImport } from './routes/portal.hotspots'
import { Route as PortalIncidentsRouteImport } from './routes/portal.incidents'
import { Route as PortalPersonnelRouteImport } from './routes/portal.personnel'
import { Route as PortalSettingsRouteImport } from './routes/portal.settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAssignmentsRoute = PortalAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => PortalRoute,
} as any)
const PortalConflictsRoute = PortalConflictsRouteImport.update({
  id: '/conflicts',
  path: '/conflicts',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDashboardRoute = PortalDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PortalRoute,
} as any)
const PortalHotspotsRoute = PortalHotspotsRouteImport.update({
  id: '/hotspots',
  path: '/hotspots',
  getParentRoute: () => PortalRoute,
} as any)
const PortalIncidentsRoute = PortalIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => PortalRoute,
} as any)
const PortalPersonnelRoute = PortalPersonnelRouteImport.update({
  id: '/personnel',
  path: '/personnel',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSettingsRoute = PortalSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PortalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/portal': typeof PortalRouteWithChildren
  '/portal/assignments': typeof PortalAssignmentsRoute
  '/portal/conflicts': typeof PortalConflictsRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/hotspots': typeof PortalHotspotsRoute
  '/portal/incidents': typeof PortalIncidentsRoute
  '/portal/personnel': typeof PortalPersonnelRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/portal/': typeof PortalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/portal/assignments': typeof PortalAssignmentsRoute
  '/portal/conflicts': typeof PortalConflictsRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/hotspots': typeof PortalHotspotsRoute
  '/portal/incidents': typeof PortalIncidentsRoute
  '/portal/personnel': typeof PortalPersonnelRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/portal': typeof PortalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/portal': typeof PortalRouteWithChildren
  '/portal/assignments': typeof PortalAssignmentsRoute
  '/portal/conflicts': typeof PortalConflictsRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/hotspots': typeof PortalHotspotsRoute
  '/portal/incidents': typeof PortalIncidentsRoute
  '/portal/personnel': typeof PortalPersonnelRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/portal/': typeof PortalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/portal'
    | '/portal/assignments'
    | '/portal/conflicts'
    | '/portal/dashboard'
    | '/portal/hotspots'
    | '/portal/incidents'
    | '/portal/personnel'
    | '/portal/settings'
    | '/portal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/portal/assignments'
    | '/portal/conflicts'
    | '/portal/dashboard'
    | '/portal/hotspots'
    | '/portal/incidents'
    | '/portal/personnel'
    | '/portal/settings'
    | '/portal'
  id:
    | '__root__'
    | '/'
    | '/portal'
    | '/portal/assignments'
    | '/portal/conflicts'
    | '/portal/dashboard'
    | '/portal/hotspots'
    | '/portal/incidents'
    | '/portal/personnel'
    | '/portal/settings'
    | '/portal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PortalRoute: typeof PortalRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/assignments': {
      id: '/portal/assignments'
      path: '/assignments'
      fullPath: '/portal/assignments'
      preLoaderRoute: typeof PortalAssignmentsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/conflicts': {
      id: '/portal/conflicts'
      path: '/conflicts'
      fullPath: '/portal/conflicts'
      preLoaderRoute: typeof PortalConflictsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/dashboard': {
      id: '/portal/dashboard'
      path: '/dashboard'
      fullPath: '/portal/dashboard'
      preLoaderRoute: typeof PortalDashboardRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/hotspots': {
      id: '/portal/hotspots'
      path: '/hotspots'
      fullPath: '/portal/hotspots'
      preLoaderRoute: typeof PortalHotspotsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/incidents': {
      id: '/portal/incidents'
      path: '/incidents'
      fullPath: '/portal/incidents'
      preLoaderRoute: typeof PortalIncidentsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/personnel': {
      id: '/portal/personnel'
      path: '/personnel'
      fullPath: '/portal/personnel'
      preLoaderRoute: typeof PortalPersonnelRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/settings': {
      id: '/portal/settings'
      path: '/settings'
      fullPath: '/portal/settings'
      preLoaderRoute: typeof PortalSettingsRouteImport
      parentRoute: typeof PortalRoute
    }
  }
}

interface PortalRouteChildren {
  PortalAssignmentsRoute: typeof PortalAssignmentsRoute
  PortalConflictsRoute: typeof PortalConflictsRoute
  PortalDashboardRoute: typeof PortalDashboardRoute
  PortalHotspotsRoute: typeof PortalHotspotsRoute
  PortalIncidentsRoute: typeof PortalIncidentsRoute
  PortalPersonnelRoute: typeof PortalPersonnelRoute
  PortalSettingsRoute: typeof PortalSettingsRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalAssignmentsRoute: PortalAssignmentsRoute,
  PortalConflictsRoute: PortalConflictsRoute,
  PortalDashboardRoute: PortalDashboardRoute,
  PortalHotspotsRoute: PortalHotspotsRoute,
  PortalIncidentsRoute: PortalIncidentsRoute,
  PortalPersonnelRoute: PortalPersonnelRoute,
  PortalSettingsRoute: PortalSettingsRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PortalRoute: PortalRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
